[Initial]
dune="A beginning is the time for taking the most delicate care that the balances are correct."
farehnheit451="It was a pleasure to burn. It was a special pleasure to see things eaten, to see things blackened and changed."
blindsight="It didn't start out here. Not with the scramblers or Rorschach, not with Big Ben or Theseus or the vampires."

[[Command]]
type="Read"
file="blindsight"

[[Command]]
type="DisableServer"
server=1

[[Command]]
type="Read"
file="blindsight"

[[Command]]
type="DisableServer"
server=2

[[Command]]
type="Read"
file="blindsight"

[[Command]]
type="DisableServer"
server=3

[[Command]]
type="Read"
file="blindsight"

[[Command]]
type="DisableServer"
server=4

[[Command]]
type="Read"
file="blindsight"

[[Command]]
type="DisableServer"
server=5

[[Command]]
type="Read"
file="blindsight"

